#oauth2 client configuration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=43282066916-u20r6un0rd28udc0ioh187jraf7mhd7u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

#github client configuration
spring.security.oauth2.client.registration.github.client-name=github
spring.security.oauth2.client.registration.github.client-id=Iv23liKfhTla42OH6j2P
spring.security.oauth2.client.registration.github.client-secret=1b4a786067faf9ff491bf6fd3fe22ad133dcb4d6
spring.security.oauth2.client.registration.github.scope=email,profile 

#cloudinary configuration
cloudinary.cloud.name=dxq7t8jjk
cloudinary.api.key=382495242619121
cloudinary.api.secret=FHCf99OnnHsCYYsIvBG-tOTlOjg


#email configuration for mailtrap
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=smtp@mailtrap.io
spring.mail.password=88578ad8628e170463ae5c63a0bfef00
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#spring boot mail starter


